# /etc/rsyslog.d/delpy.conf

input(
    type="imfile"
    File="/opt/delpy/logs/delpy.log"
    Tag="delpy"
    Facility="local6"
    Severity="info"
    PersistStateInterval="100"
)

if $programname == "delpy" then {
    action(
        type="omfwd"
        Target="<SYSLOG-HOST>"
        Port="514"
        Protocol="tcp"
        TCP_Framing="octet-counted"
        KeepAlive="on"
        Action.ResumeRetryCount="-1"
    )
    stop
}

